server:
  port: 7000 
spring:
   application:
    name: auth-service 
   config:
    import: configserver:http://localhost:8888
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.uuid}         

management:
  endpoints:
    web:
      exposure:
        include:
          "*"
       
  
