server:
  port: 8000
spring:
   application:
    name: advertise-service  
   config:
    import: configserver:http://localhost:8888 
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.uuid}   
  